revoke delete on table "public"."third" from "anon";

revoke insert on table "public"."third" from "anon";

revoke references on table "public"."third" from "anon";

revoke select on table "public"."third" from "anon";

revoke trigger on table "public"."third" from "anon";

revoke truncate on table "public"."third" from "anon";

revoke update on table "public"."third" from "anon";

revoke delete on table "public"."third" from "authenticated";

revoke insert on table "public"."third" from "authenticated";

revoke references on table "public"."third" from "authenticated";

revoke select on table "public"."third" from "authenticated";

revoke trigger on table "public"."third" from "authenticated";

revoke truncate on table "public"."third" from "authenticated";

revoke update on table "public"."third" from "authenticated";

revoke delete on table "public"."third" from "service_role";

revoke insert on table "public"."third" from "service_role";

revoke references on table "public"."third" from "service_role";

revoke select on table "public"."third" from "service_role";

revoke trigger on table "public"."third" from "service_role";

revoke truncate on table "public"."third" from "service_role";

revoke update on table "public"."third" from "service_role";

alter table "public"."third" drop constraint "third_pkey";

drop index if exists "public"."third_pkey";

drop table "public"."third";

create table "public"."foourth" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."foourth" enable row level security;

CREATE UNIQUE INDEX foourth_pkey ON public.foourth USING btree (id);

alter table "public"."foourth" add constraint "foourth_pkey" PRIMARY KEY using index "foourth_pkey";

grant delete on table "public"."foourth" to "anon";

grant insert on table "public"."foourth" to "anon";

grant references on table "public"."foourth" to "anon";

grant select on table "public"."foourth" to "anon";

grant trigger on table "public"."foourth" to "anon";

grant truncate on table "public"."foourth" to "anon";

grant update on table "public"."foourth" to "anon";

grant delete on table "public"."foourth" to "authenticated";

grant insert on table "public"."foourth" to "authenticated";

grant references on table "public"."foourth" to "authenticated";

grant select on table "public"."foourth" to "authenticated";

grant trigger on table "public"."foourth" to "authenticated";

grant truncate on table "public"."foourth" to "authenticated";

grant update on table "public"."foourth" to "authenticated";

grant delete on table "public"."foourth" to "service_role";

grant insert on table "public"."foourth" to "service_role";

grant references on table "public"."foourth" to "service_role";

grant select on table "public"."foourth" to "service_role";

grant trigger on table "public"."foourth" to "service_role";

grant truncate on table "public"."foourth" to "service_role";

grant update on table "public"."foourth" to "service_role";


