create table "public"."third" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."third" enable row level security;

CREATE UNIQUE INDEX third_pkey ON public.third USING btree (id);

alter table "public"."third" add constraint "third_pkey" PRIMARY KEY using index "third_pkey";

grant delete on table "public"."third" to "anon";

grant insert on table "public"."third" to "anon";

grant references on table "public"."third" to "anon";

grant select on table "public"."third" to "anon";

grant trigger on table "public"."third" to "anon";

grant truncate on table "public"."third" to "anon";

grant update on table "public"."third" to "anon";

grant delete on table "public"."third" to "authenticated";

grant insert on table "public"."third" to "authenticated";

grant references on table "public"."third" to "authenticated";

grant select on table "public"."third" to "authenticated";

grant trigger on table "public"."third" to "authenticated";

grant truncate on table "public"."third" to "authenticated";

grant update on table "public"."third" to "authenticated";

grant delete on table "public"."third" to "service_role";

grant insert on table "public"."third" to "service_role";

grant references on table "public"."third" to "service_role";

grant select on table "public"."third" to "service_role";

grant trigger on table "public"."third" to "service_role";

grant truncate on table "public"."third" to "service_role";

grant update on table "public"."third" to "service_role";


